FROM chrishyze/extended-php:{{ tag }}

LABEL version="1.0"
LABEL org.opencontainers.image.authors="chrishyze@gmail.com"

RUN set -ex &&\
    apt-get update &&\
    apt-get install -y wget unzip {{ packages }} &&\
    apt-get autoclean &&\
    mkdir -p /usr/local/bin &&\
    wget -O /usr/local/bin/composer https://getcomposer.org/download/latest-stable/composer.phar &&\
    chmod +x /usr/local/bin/composer &&\
    mkdir -p /usr/local/src &&\
    wget -O /usr/local/src/zblogphp.zip https://github.com/zblogcn/zblogphp/releases/latest/download/zblogphp.zip &&\
    mv /var/www/html /var/www/zblogphp &&\
    unzip -o /usr/local/src/zblogphp.zip -d /var/www/zblogphp &&\
    chown -R www-data:www-data /var/www/zblogphp &&\
    chmod -R 0755 /var/www/zblogphp &&\
{% for cmd in extra_run_cmds %}
    {{ cmd|raw }}{% if not loop.last %} &&\
{% endif %}
{% endfor %}

WORKDIR /var/www/zblogphp
