name: Publish 8.1-fpm-alpine

on:
  push:
    branches:
      - publish

jobs:
  publish_81_fpm_alpine_mysql:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/fpm-alpine/mysql/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zblogphp:8.1-fpm-alpine,${{ secrets.DOCKERHUB_USERNAME }}/zblogphp:latest
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
  publish_81_fpm_alpine_pgsql:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/fpm-alpine/pgsql/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zblogphp:8.1-fpm-alpine-pgsql,${{ secrets.DOCKERHUB_USERNAME }}/zblogphp:latest
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
  publish_81_fpm_alpine_dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "dockerfile/8.1/fpm-alpine/dev/Dockerfile"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zblogphp:8.1-fpm-alpine-dev,${{ secrets.DOCKERHUB_USERNAME }}/zblogphp:latest
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
